package Vistas;

import AccesoDatos.AlumnoData;
import Entidades.Alumno;
import com.toedter.calendar.JTextFieldDateEditor;
import java.sql.Date;
import java.time.LocalDate;
import java.time.Month;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import java.util.regex.*;

public class FormularioAlumno extends javax.swing.JInternalFrame {
    
    private Alumno alumno = null;
    private AlumnoData acceso = new AlumnoData();

    /**
     * Creates new form FormularioAlumno
     */
    public FormularioAlumno() {
        initComponents();
        btnEliminarAlumno.setEnabled(false);
        editorJcalendar = (JTextFieldDateEditor) jdNacimiento.getDateEditor();
        editorJcalendar.setEditable(false);
        jdNacimiento.setDate(Date.valueOf((LocalDate.of(2006, Month.JANUARY, 01))));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarAlumno = new javax.swing.JButton();
        btnNuevoAlumno = new javax.swing.JButton();
        btnEliminarAlumno = new javax.swing.JButton();
        btnGuardarAlumno = new javax.swing.JButton();
        btnSalirAlumno = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtApellido = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtDni = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jLabel5 = new javax.swing.JLabel();
        jdNacimiento = new com.toedter.calendar.JDateChooser();
        jLabel6 = new javax.swing.JLabel();

        btnBuscarAlumno.setText("Buscar");
        btnBuscarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarAlumnoActionPerformed(evt);
            }
        });

        btnNuevoAlumno.setText("Nuevo");
        btnNuevoAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoAlumnoActionPerformed(evt);
            }
        });

        btnEliminarAlumno.setText("Eliminar");
        btnEliminarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarAlumnoActionPerformed(evt);
            }
        });

        btnGuardarAlumno.setText("Guardar");
        btnGuardarAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarAlumnoActionPerformed(evt);
            }
        });

        btnSalirAlumno.setText("Salir");
        btnSalirAlumno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirAlumnoActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Documento:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Apellido:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("Nombre:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setText("Estado:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setText("Fecha de Nacimiento:");

        jdNacimiento.setMaxSelectableDate(new java.util.Date(1167624084000L));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel6.setText("Alumno");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(56, 56, 56)
                                .addComponent(jrbEstado))
                            .addComponent(jLabel5)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(34, 34, 34)
                                .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarAlumno)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevoAlumno)
                                .addGap(43, 43, 43)
                                .addComponent(btnEliminarAlumno)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jdNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnGuardarAlumno)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnSalirAlumno))))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtApellido)
                                    .addComponent(txtNombre))))
                        .addGap(53, 53, 53))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(214, 214, 214))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel6)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtDni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarAlumno))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jrbEstado))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jdNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevoAlumno)
                    .addComponent(btnEliminarAlumno)
                    .addComponent(btnGuardarAlumno)
                    .addComponent(btnSalirAlumno))
                .addGap(62, 62, 62))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirAlumnoActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirAlumnoActionPerformed

    private void btnBuscarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarAlumnoActionPerformed
        // TODO add your handling code here:

        Date nacimiento = new Date(0);
        if (patronDni(txtDni.getText())) {
            JOptionPane.showMessageDialog(rootPane, "porfavor inserte un dni valido(solo numeros max8)");
            txtDni.requestFocus();
            return;
        } else {
            
            if (txtDni.getText().toString().length() != 0) {
                alumno = acceso.buscarAlumnoPorDni(Integer.valueOf(txtDni.getText()));
            } else {
                JOptionPane.showMessageDialog(rootPane, "por favor rellene el campo dni");
                return;
            }
            
            if (alumno != null) {
                nacimiento = Date.valueOf(alumno.getFechaNacimiento());
                jrbEstado.setSelected(alumno.isEstado());
                jdNacimiento.setDate(nacimiento);
                txtApellido.setText(alumno.getApellido());
                txtNombre.setText(alumno.getNombre());
                btnEliminarAlumno.setEnabled(true);
            }
            
        }
        

    }//GEN-LAST:event_btnBuscarAlumnoActionPerformed

    private void btnNuevoAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoAlumnoActionPerformed
        // TODO add your handling code here:
        txtDni.setText("");
        jrbEstado.setSelected(false);
        jdNacimiento.setDate(Date.valueOf((LocalDate.of(2006, Month.JANUARY, 01))));
        txtApellido.setText("");
        txtNombre.setText("");
        btnEliminarAlumno.setEnabled(false);
        alumno = null;

    }//GEN-LAST:event_btnNuevoAlumnoActionPerformed

    private void btnEliminarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarAlumnoActionPerformed
        // TODO add your handling code here:

        alumno = acceso.buscarAlumnoPorDni(Integer.valueOf(txtDni.getText()));
        acceso.eliminarAlumno(alumno.getIdAlumno());

        //limpieza de campos y desabilitacion del boton
        btnNuevoAlumnoActionPerformed(evt);
        

    }//GEN-LAST:event_btnEliminarAlumnoActionPerformed

    private void btnGuardarAlumnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarAlumnoActionPerformed
        // TODO add your handling code here:

        if (alumno == null) {
            guardarAlumno();
            btnNuevoAlumnoActionPerformed(evt);
        } else {
            editarAlumno();
            btnNuevoAlumnoActionPerformed(evt);
        }
        

    }//GEN-LAST:event_btnGuardarAlumnoActionPerformed
    
    private boolean patronDni(String dni) {
        //TRUE si el dni contiene cualquier cosa que no sea un numero
        Pattern patron = Pattern.compile("\\D+|.{9,}");
        Matcher comparador = patron.matcher(dni);
        
        return comparador.find();
    }

    //guardaralumno
    private void guardarAlumno() {
        Alumno alumnonuevo = new Alumno();
        if (txtDni.getText().isEmpty()|| patronDni(txtDni.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un valor numerico valido en el dni");
            txtDni.requestFocus();
            return;
        } else if (txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un valor valido en el apellido");
            txtApellido.requestFocus();
            return;
        } else if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un valor valido en el nombre");
            txtNombre.requestFocus();
            return;
        }
        
        alumnonuevo.setDni(Integer.parseInt(txtDni.getText()));
        alumnonuevo.setApellido(txtApellido.getText());
        alumnonuevo.setNombre(txtNombre.getText());
        alumnonuevo.setEstado(jrbEstado.isSelected());
        alumnonuevo.setFechaNacimiento(jdNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        
        alumno = alumnonuevo;
        acceso.guardarAlumno(alumno);
        
    }

    //editarAlumno
    private void editarAlumno() {
        
        if (txtDni.getText().isEmpty() || patronDni(txtDni.getText())) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un valor numerico valido en el dni");
            txtDni.requestFocus();
            return;
        } else if (txtApellido.getText().isEmpty() ) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un valor valido en el apellido");
            txtApellido.requestFocus();
            return;
        } else if (txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Por favor ingrese un valor valido en el nombre");
            txtNombre.requestFocus();
            return;
        }
        
        alumno.setDni(Integer.valueOf(txtDni.getText()));
        alumno.setApellido(txtApellido.getText());
        alumno.setNombre(txtNombre.getText());
        alumno.setEstado(jrbEstado.isSelected());
        alumno.setFechaNacimiento(jdNacimiento.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
        acceso.modificarAlumno(alumno);
        
    }

    //editor de texto del jdatechooser
    JTextFieldDateEditor editorJcalendar;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarAlumno;
    private javax.swing.JButton btnEliminarAlumno;
    private javax.swing.JButton btnGuardarAlumno;
    private javax.swing.JButton btnNuevoAlumno;
    private javax.swing.JButton btnSalirAlumno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private com.toedter.calendar.JDateChooser jdNacimiento;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDni;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
